### ISSUE TITLE
Document firmware

### ISSUE THREAD

**Issue by SRGDamia1** [NorthernWidget-Skunkworks/Project-TPDH-Walrus#13]
There needs to be clear documentation of the communication protocol.  What commands must be sent to begin sampling?  What data will be in what register on what time scale?

**Comment by awickert** [comment]
Full documentation for the logger firmware is available in the associated GitHub repository:
https://github.com/NorthernWidget-Skunkworks/Walrus_Library

I have now added a note to this effect and a link at the start of the programming examples below.
fab5c4cd1c0b618f8ebd5077d62c193e57c66981
